const validations = {
    name: (value) => !!value || "Por favor, insira o nome do usuário.",
    last_name: (value) => !!value || "Por favor, insira o sobrenome do usuário.",
    email: (value) => !!value.match(/^\S+@\S+\.\S+$/) || "Por favor, insira um email válido.",
    phone: (value) => !!value || "Por favor, insira o telefone do usuário.",
    cpf: (value) => !!value.match(/^\d{3}\.\d{3}\.\d{3}-\d{2}$/) || "Por favor, insira um CPF válido.",
    password: (value) => value?.length >= 6 || "A senha deve ter pelo menos 6 caracteres.",
    cep: (value) => !!value || "Por favor, insira o CEP.",
    city: (value) => !!value || "Por favor, insira a cidade.",
    state: (value) => !!value || "Por favor, insira o estado.",
    street: (value) => !!value || "Por favor, insira a rua.",
    razao_social: (value) => !!value || "Por favor, insira a razão social.",
    nome_fantasia: (value) => !!value || "Por favor, insira o nome fantasia.",
    nome_responsavel: (value) => !!value || "Por favor, insira o nome do responsável.",
    email_responsavel: (value) => !!value.match(/^\S+@\S+\.\S+$/) || "Por favor, insira um email válido do responsável.",
    cpf_responsavel: (value) => !!value.match(/^\d{3}\.\d{3}\.\d{3}-\d{2}$/) || "Por favor, insira um CPF válido do responsável.",
    telefone_responsavel: (value) => !!value || "Por favor, insira o telefone do responsável.",
    cnpj: (value) => !!value.match(/^\d{2}\.\d{3}\.\d{3}\/\d{4}-\d{2}$/) || "Por favor, insira um CNPJ válido.",
    preco: (value) => !!value || "Por favor, insira o preço do produto.",
    quantidade: (value) => !!value || "Por favor, insira a quantidade do produto.",
    validade: (value) => !!value || "Por favor, insira a validade do produto.",
    lote: (value) => !!value || "Por favor, insira o lote do produto.",
    descricao: (value) => !!value || "Por favor, insira a descrição do produto.",
};
export default validations;